[package]
name = "fork"
version = "0.1.4"
authors = ["Nicolas Embriz <nbari@tequila.io>"]
description = "Library for creating a new process detached from the controling terminal (daemon)"
documentation = "https://github.com/immortal/fork"
homepage = "https://github.com/immortal/fork"
repository = "https://github.com/immortal/fork"
readme = "README.md"
keywords = ["fork", "setsid", "daemon", "process", "libc"]
categories = ["command-line-utilities", "os"]
license-file = "LICENSE"
edition = "2018"

[dependencies]
libc = "0.2.65"
